name: ChatChat Version Docker Image CI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"

      - name: Build multi-platform Docker image
        run: docker buildx create --use && docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.actor }}/chatchat:latest .

      - name: Push multi-platform Docker image to GHCR
        run: |
          docker buildx create --use && docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.actor }}/chatchat:latest --push

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag multi-platform Docker image for Docker Hub
        run: |
          docker buildx create --use && docker buildx build --platform linux/amd64,linux/arm64 -t ${{ github.actor }}/chatchat:latest .

      - name: Push multi-platform Docker image to Docker Hub
        run: |
          docker buildx create --use && docker buildx build --platform linux/amd64,linux/arm64 -t ${{ github.actor }}/chatchat:latest --push
