name: Docker Image CI

on:
    release:
        types: [created]

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build Docker image
              run: docker build -t ghcr.io/okisdev/chatchat:${{ github.ref }} .
            - name: Push Docker image
              run: docker push ghcr.io/okisdev/chatchat:${{ github.ref }}
